<?php

return [
    'samboan' => [
        "Barangay Basak",
        "Barangay Bonbon",
        "Barangay Bulangsuran",
        "Barangay Calatagan",
        "Barangay Cambigong",
        "Barangay Camburoy",
        "Barangay Canorong",
        "Barangay Colase",
        "Barangay Dalahikan",
        "Barangay Jumangpas",
        "Barangay Monteverde",
        "Barangay Poblacion",
        "Barangay San Sebastian",
        "Barangay Suba",
        "Barangay Tangbo",
    ],

    'oslob' => [
        "Barangay Alo",
        "Barangay Bangcogon",
        "Barangay Bonbon",
        "Barangay Calumpang",
        "Barangay Canangca-an",
        "Barangay Cansalo-ay",
        "Barangay Can-ukban",
        "Barangay Cañang",
        "Barangay Daanlungsod",
        "Barangay Gawi",
        "Barangay Hagdan",
        "Barangay Lagunde",
        "Barangay Looc",
        "Barangay Luka",
        "Barangay Mainit",
        "Barangay Manlum",
        "Barangay Nueva Caceres",
        "Barangay Poblacion",
        "Barangay Pungtod",
        "Barangay Tan-awan",
        "Barangay Tumalog",
    ],

    'tuburan' => [
        "Barangay Apalan",
        "Barangay Bagasawe",
        "Barangay Bagasawe",
        "Barangay Bakyawan",
        "Barangay Bulwang",
        "Barangay Carmen",
        "Barangay Daanlungsod",
        "Barangay Kabangkalan",
        "Barangay Kalangahan",
        "Barangay Kampingganon",
        "Barangay Kumalisquis",
        "Barangay Mag-Antoy",
        "Barangay Mahanlud",
        "Barangay Poblacion",
        "Barangay San Juan",
        "Barangay Sandayong",
        "Barangay Sto. Niño",
        "Barangay Siotes",
        "Barangay Tigbawan",
        "Barangay Tomonoy",
    ],
    'moalboal' => [
        "Barangay Agbalanga",
        "Barangay Bala",
        "Barangay Balabagon",
        "Barangay Basdiot",
        "Barangay Batadbatad",
        "Barangay Bugho",
        "Barangay Buguil",
        "Barangay Busay",
        "Barangay Lanao",
        "Barangay Poblacion East",
        "Barangay Poblacion West",
        "Barangay Saavedra",
        "Barangay Tomonoy",
        "Barangay Tuble",
        "Barangay Tunga",

    ],
    'aloguinsan' => [
        "Barangay Angilan",
        "Barangay Bojo",
        "Barangay Bonbon",
        "Barangay Esperanza",
        "Barangay Kandingan",
        "Barangay Kantabogon",
        "Barangay Kawasan",
        "Barangay Olango",
        "Barangay Poblacion",
        "Barangay Punay",
        "Barangay Rosario",
        "Barangay Saksak",
        "Barangay Tampa‑an",
        "Barangay Toyokon",
        "Barangay Zaragosa",

    ],
    'alegria' => [
        "Barangay Compostela",
        "Barangay Guadalupe",
        "Barangay Legaspi",
        "Barangay Lepanto",
        "Barangay Madridejos",
        "Barangay Montpeller",
        "Barangay Poblacion",
        "Barangay Santa Filomena",
        "Barangay Valencia ",
    ],
    'tuburan' => [
        "Barangay Alegria",
        "Barangay Amatugan",
        "Barangay Antipolo",
        "Barangay Apalan",
        "Barangay Bagasawe",
        "Barangay Bakyawan",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay VI",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay Bulwang",
        "Barangay Caridad ",
        "Barangay Carmelo ",
        "Barangay Cogon ",
        "Barangay Colonia ",
        "Barangay Daan Lungsod ",
        "Barangay Fortaliza ",
        "Barangay Ga‑ang ",
        "Barangay Gimama‑a ",
        "Barangay Jagbuaya ",
        "Barangay Kabangkalan ",
        "Barangay Kabkaban ",
        "Barangay Kagba‑o ",
        "Barangay Kalangahan ",
        "Barangay Kamansi ",
        "Barangay Kampoot ",
        "Barangay Kan‑an ",
        "Barangay Kanlunsing ",
        "Barangay Kansi ",
        "Barangay Kaorasan ",
        "Barangay Libo ",
        "Barangay Lusong ",
        "Barangay Macupa ",
        "Barangay Mag‑alwa ",
        "Barangay Mag‑antoy ",
        "Barangay Mag‑atubang ",
        "Barangay Maghan‑ay ",
        "Barangay Mangga ",
        "Barangay Marmol ",
        "Barangay Molobolo ",
        "Barangay Montealegre ",
        "Barangay Putat ",
        "Barangay San Juan ",
        "Barangay Sandayong ",
        "Barangay Santo Niño ",
        "Barangay Siotes ",
        "Barangay Sumon ",
        "Barangay Tominjao ",
        "Barangay Tomugpa ",
        
    ],
    'ginatilan' => [
        "Barangay Anao",
        "Barangay Cagsing",
        "Barangay Calabawan",
        "Barangay Cambagte",
        "Barangay Campisong",
        "Barangay Cañorong",
        "Barangay Guiwanon",
        "Barangay Looc",
        "Barangay Malatbo",
        "Barangay Mangaco",
        "Barangay Palanas",
        "Barangay Poblacion",
        "Barangay Salamanca",
        "Barangay San Roque",
    ],

    'balamban' => [
        "Barangay Abucayan",
        "Barangay Aliwanay",
        "Barangay Arpili",
        "Barangay Baliwagan",
        "Barangay Bayong",
        "Barangay Biasong",
        "Barangay Buanoy",
        "Barangay Cabagdalan",
        "Barangay Cabasiangan",
        "Barangay Cambuhawe",
        "Barangay Cansomoroy",
        "Barangay Cantibas",
        "Barangay Cantuod",
        "Barangay Duangan",
        "Barangay Gaas",
        "Barangay Ginatilan",
        "Barangay Hingatmonan",
        "Barangay Lamesa",
        "Barangay Liki",
        "Barangay Luca",
        "Barangay Matun-og",
        "Barangay Nangka",
        "Barangay Pondol",
        "Barangay Prenza",
        "Barangay Santa Cruz-Santo Niño",
        "Barangay Singsing",
        "Barangay Sunog",
        "Barangay Vito",
    ],

    'poro' => [
        "Barangay Adela",
        "Barangay Altavista",
        "Barangay Cagcagan",
        "Barangay Cansabusab",
        "Barangay Daan Paz",
        "Barangay Eastern Poblacion",
        "Barangay Esperanza",
        "Barangay Libertad",
        "Barangay Mabini",
        "Barangay Mercedes",
        "Barangay Pagsa",
        "Barangay Paz",
        "Barangay Rizal",
        "Barangay San Jose",
        "Barangay Santa Rita",
        "Barangay Teguis",
        "Barangay Western Poblacion",
    ],

    'sanfrancisco' => [
        "Barangay Cabunga-an",
        "Barangay Campo",
        "Barangay Consuelo",
        "Barangay Esperanza",
        "Barangay Heminsulan",
        "Barangay Montealegre",
        "Barangay Northern Poblacion",
        "Barangay San Isidro",
        "Barangay Santa Cruz",
        "Barangay Santiago",
        "Barangay Sonog",
        "Barangay Southern Poblacion",
        "Barangay Unidos",
        "Barangay Union",
        "Barangay Western Poblacion",
    ],

    'tudela' => [
        "Barangay Buenavista",
        "Barangay Calmante",
        "Barangay Daan Secante",
        "Barangay General",
        "Barangay McArthur",
        "Barangay Northern Poblacion",
        "Barangay Puertobello",
        "Barangay Santander",
        "Barangay Secante Bag-o",
        "Barangay Southern Poblacion",
        "Barangay Villahermosa",
    ],

    'pilar' => [
        "Barangay Biasong",
        "Barangay Cawit",
        "Barangay Dapdap",
        "Barangay Esperanza",
        "Barangay Imelda",
        "Barangay Lanao",
        "Barangay Lower Poblacion",
        "Barangay Moabog",
        "Barangay Montserrat",
        "Barangay San Isidro",
        "Barangay San Juan",
        "Barangay Upper Poblacion",
        "Barangay Villahermosa",
    ],

    'danao' => [
        "Barangay Baliang",
        "Barangay Bayabas",
        "Barangay Binaliw",
        "Barangay Cabungahan",
        "Barangay Cagat-Lamac",
        "Barangay Cahumayan",
        "Barangay Cambanay",
        "Barangay Cambubho",
        "Barangay Cogon-Cruz",
        "Barangay Danasan",
        "Barangay Dungga",
        "Barangay Dunggoan",
        "Barangay Guinacot",
        "Barangay Guinsay",
        "Barangay Ibo",
        "Barangay Langosig",
        "Barangay Lawaan",
        "Barangay Licos",
        "Barangay Looc",
        "Barangay Magtagobtob",
        "Barangay Malapoc",
        "Barangay Manlayag",
        "Barangay Mantija",
        "Barangay Masaba",
        "Barangay Maslog",
        "Barangay Nangka",
        "Barangay Oguis",
        "Barangay Pili",
        "Barangay Poblacion",
        "Barangay Quisol",
        "Barangay Sabang",
        "Barangay Sacsac",
        "Barangay Sandayong Norte",
        "Barangay Sandayong Sur",
        "Barangay Santa Rosa",
        "Barangay Santican",
        "Barangay Sibacan",
        "Barangay Suba",
        "Barangay Taboc",
        "Barangay Taytay",
        "Barangay Togonon",
        "Barangay Tuburan Sur",
    ],

    'badian' => [
        "Barangay Alawijao",
        "Barangay Balhaan",
        "Barangay Banhigan",
        "Barangay Basak",
        "Barangay Basiao",
        "Barangay Bato",
        "Barangay Bugas",
        "Barangay Calangcang",
        "Barangay Candiis",
        "Barangay Dagatan",
        "Barangay Dobdob",
        "Barangay Ginablan",
        "Barangay Lambug",
        "Barangay Malabago",
        "Barangay Malhiao",
        "Barangay Manduyong",
        "Barangay Matutinao",
        "Barangay Patong",
        "Barangay Poblacion",
        "Barangay Sanlagan",
        "Barangay Santicon",
        "Barangay Sohoton",
        "Barangay Sulsugan",
        "Barangay Talayong",
        "Barangay Taytay",
        "Barangay Tigbao",
        "Barangay Tiguib",
        "Barangay Tubod",
        "Barangay Zaragosa",
    ],

    'dumanjug' => [
        "Barangay Balaygtiki",
        "Barangay Bitoon",
        "Barangay Bulak",
        "Barangay Bullogan",
        "Barangay Doldol",
        "Barangay Kabalaasnan",
        "Barangay Kabatbatan",
        "Barangay Calaboon",
        "Barangay Kambanog",
        "Barangay Camboang",
        "Barangay Candabong",
        "Barangay Kang-actol",
        "Barangay Kanghalo",
        "Barangay Kanghumaod",
        "Barangay Kanguha",
        "Barangay Kantangkas",
        "Barangay Kanyuko",
        "Barangay Cogon",
        "Barangay Kolabtingon",
        "Barangay Cotcoton",
        "Barangay Lamak",
        "Barangay Lawaan",
        "Barangay Liong",
        "Barangay Manlapay",
        "Barangay Masa",
        "Barangay Matalao",
        "Barangay Paculob",
        "Barangay Panlaan",
        "Barangay Pawa",
        "Barangay Ilaya",
        "Barangay Poblacion Looc",
        "Barangay Poblacion Sima",
        "Barangay Tangil",
        "Barangay Tapon",
        "Barangay Tubod-Bitoon",
        "Barangay Tubod-Dugoan",
        "Barangay Poblacion Central",
    ],

    'malabuyoc' => [
        "Barangay Armeña",
        "Barangay Tolosa",
        "Barangay Cerdeña",
        "Barangay Labrador",
        "Barangay Looc",
        "Barangay Lombo",
        "Barangay Mahanlud",
        "Barangay Mindanao",
        "Barangay Montañeza",
        "Barangay Salmeron",
        "Barangay Santo Niño",
        "Barangay Sorsogon",
        "Barangay I",
        "Barangay II",
    ],

    'alcoy' => [
        "Barangay Atabay",
        "Barangay Daan-Lungsod",
        "Barangay Guiwang",
        "Barangay Nug-as",
        "Barangay Pasol",
        "Barangay Poblacion",
        "Barangay Pugalo",
        "Barangay San Agustin",
    ],

    'dalaguete' => [
        "Barangay Ablayan",
        "Barangay Babayongan",
        "Barangay Balud",
        "Barangay Banhigan",
        "Barangay Bulak",
        "Barangay Caliongan",
        "Barangay Caleriohan",
        "Barangay Casay",
        "Barangay Catolohan",
        "Barangay Cawayan",
        "Barangay Consolacion",
        "Barangay Coro",
        "Barangay Dugyan",
        "Barangay Dumalan",
        "Barangay Jolomaynon",
        "Barangay Lanao",
        "Barangay Langkas",
        "Barangay Lumbang",
        "Barangay Malones",
        "Barangay Maloray",
        "Barangay Mananggal",
        "Barangay Manlapay",
        "Barangay Mantalongon",
        "Barangay Nalhub",
        "Barangay Obo",
        "Barangay Obong",
        "Barangay Panas",
        "Barangay Poblacion",
        "Barangay Sacsac",
        "Barangay Tapun",
        "Barangay Tuba",
        "Barangay Salug",
        "Barangay Tabon",
    ],

    'argao' => [
        "Barangay Alambijud",
        "Barangay Anajao",
        "Barangay Apo",
        "Barangay Balaas",
        "Barangay Balisong",
        "Barangay Binlod",
        "Barangay Bogo",
        "Barangay Butong",
        "Barangay Bug-ot",
        "Barangay Bulasa",
        "Barangay Calagasan",
        "Barangay Canbantug",
        "Barangay Canbanua",
        "Barangay Cansuje",
        "Barangay Capio-an",
        "Barangay Casay",
        "Barangay Catang",
        "Barangay Colawin",
        "Barangay Conalum",
        "Barangay Guiwanon",
        "Barangay Gutlang",
        "Barangay Jampang",
        "Barangay Jomgao",
        "Barangay Lamacan",
        "Barangay Langtad",
        "Barangay Langub",
        "Barangay Lapay",
        "Barangay Lengigon",
        "Barangay Linut-od",
        "Barangay Mabasa",
        "Barangay Mandilikit",
        "Barangay Mompeller",
        "Barangay Panadtaran",
        "Barangay Poblacion",
        "Barangay Sua",
        "Barangay Sumaguan",
        "Barangay Tabayag",
        "Barangay Talaga",
        "Barangay Talaytay",
        "Barangay Talo-ot",
        "Barangay Tiguib",
        "Barangay Tulang",
        "Barangay Tulic",
        "Barangay Ubaub",
        "Barangay Usmad",
    ],

    'barili' => [
        "Barangay Azucena",
        "Barangay Bagakay",
        "Barangay Balao",
        "Barangay Bolocboloc",
        "Barangay Budbud",
        "Barangay Bugtong Kawayan",
        "Barangay Cabcaban",
        "Barangay Campangga",
        "Barangay Dakit",
        "Barangay Giloctog",
        "Barangay Guibuangan",
        "Barangay Giwanon",
        "Barangay Gunting",
        "Barangay Hilasgasan",
        "Barangay Japitan",
        "Barangay Cagay",
        "Barangay Kalubihan",
        "Barangay Kangdampas",
        "Barangay Candugay",
        "Barangay Luhod",
        "Barangay Lupo",
        "Barangay Luyo",
        "Barangay Maghanoy",
        "Barangay Maigang",
        "Barangay Malolos",
        "Barangay Mantalongon",
        "Barangay Mantayupan",
        "Barangay Mayana",
        "Barangay Minolos",
        "Barangay Nabunturan",
        "Barangay Nasipit",
        "Barangay Pancil",
        "Barangay Pangpang",
        "Barangay Paril",
        "Barangay Patupat",
        "Barangay Poblacion",
        "Barangay San Rafael",
        "Barangay Santa Ana",
        "Barangay Sayaw",
        "Barangay Tal-ot",
        "Barangay Tubod",
        "Barangay Vito",
    ],

    'naga' => [
        "Barangay Alfaco",
        "Barangay Bairan",
        "Barangay Balirong",
        "Barangay Cabungahan",
        "Barangay Cantao-an",
        "Barangay Central Poblacion",
        "Barangay Cogon",
        "Barangay Colon",
        "Barangay East Poblacion",
        "Barangay Inayagan",
        "Barangay Inoburan",
        "Barangay Jaguimit",
        "Barangay Lanas",
        "Barangay Langtad",
        "Barangay Lutac",
        "Barangay Mainit",
        "Barangay Mayana",
        "Barangay Naalad",
        "Barangay North Poblacion",
        "Barangay Pangdan",
        "Barangay Patag",
        "Barangay South Poblacion",
        "Barangay Tagjaguimit",
        "Barangay Tangke",
        "Barangay Tinaan",
        "Barangay Tuyan",
        "Barangay Uling",
        "Barangay West Poblacion",
    ],

    'cordova' => [
        "Barangay Alegria",
        "Barangay Bangbang",
        "Barangay Buagsong",
        "Barangay Catarman",
        "Barangay Cogon",
        "Barangay Dapitan",
        "Barangay Day-as",
        "Barangay Gabi",
        "Barangay Gilutongan",
        "Barangay Ibabao",
        "Barangay Pilipog",
        "Barangay Poblacion",
        "Barangay San Miguel",
    ],

];