<?php

return [
    'samboan' => [
        "Barangay Basak",
        "Barangay Bonbon",
        "Barangay Bulangsuran",
        "Barangay Calatagan",
        "Barangay Cambigong",
        "Barangay Camburoy",
        "Barangay Canorong",
        "Barangay Colase",
        "Barangay Dalahikan",
        "Barangay Jumangpas",
        "Barangay Monteverde",
        "Barangay Poblacion",
        "Barangay San Sebastian",
        "Barangay Suba",
        "Barangay Tangbo",
    ],

    'oslob' => [
        "Barangay Alo",
        "Barangay Bangcogon",
        "Barangay Bonbon",
        "Barangay Calumpang",
        "Barangay Canangca-an",
        "Barangay Cansalo-ay",
        "Barangay Can-ukban",
        "Barangay Cañang",
        "Barangay Daanlungsod",
        "Barangay Gawi",
        "Barangay Hagdan",
        "Barangay Lagunde",
        "Barangay Looc",
        "Barangay Luka",
        "Barangay Mainit",
        "Barangay Manlum",
        "Barangay Nueva Caceres",
        "Barangay Poblacion",
        "Barangay Pungtod",
        "Barangay Tan-awan",
        "Barangay Tumalog",
    ],

    'tuburan' => [
        "Barangay Apalan",
        "Barangay Bagasawe",
        "Barangay Bagasawe",
        "Barangay Bakyawan",
        "Barangay Bulwang",
        "Barangay Carmen",
        "Barangay Daanlungsod",
        "Barangay Kabangkalan",
        "Barangay Kalangahan",
        "Barangay Kampingganon",
        "Barangay Kumalisquis",
        "Barangay Mag-Antoy",
        "Barangay Mahanlud",
        "Barangay Poblacion",
        "Barangay San Juan",
        "Barangay Sandayong",
        "Barangay Sto. Niño",
        "Barangay Siotes",
        "Barangay Tigbawan",
        "Barangay Tomonoy",
    ],
    'moalboal' => [
        "Barangay Agbalanga",
        "Barangay Bala",
        "Barangay Balabagon",
        "Barangay Basdiot",
        "Barangay Batadbatad",
        "Barangay Bugho",
        "Barangay Buguil",
        "Barangay Busay",
        "Barangay Lanao",
        "Barangay Poblacion East",
        "Barangay Poblacion West",
        "Barangay Saavedra",
        "Barangay Tomonoy",
        "Barangay Tuble",
        "Barangay Tunga",

    ],
];