<?php

return [
    'samboan' => [
        "Barangay Basak",
        "Barangay Bonbon",
        "Barangay Bulangsuran",
        "Barangay Calatagan",
        "Barangay Cambigong",
        "Barangay Camburoy",
        "Barangay Canorong",
        "Barangay Colase",
        "Barangay Dalahikan",
        "Barangay Jumangpas",
        "Barangay Monteverde",
        "Barangay Poblacion",
        "Barangay San Sebastian",
        "Barangay Suba",
        "Barangay Tangbo",
    ],

    'oslob' => [
        "Barangay Alo",
        "Barangay Bangcogon",
        "Barangay Bonbon",
        "Barangay Calumpang",
        "Barangay Canangca-an",
        "Barangay Cansalo-ay",
        "Barangay Can-ukban",
        "Barangay Cañang",
        "Barangay Daanlungsod",
        "Barangay Gawi",
        "Barangay Hagdan",
        "Barangay Lagunde",
        "Barangay Looc",
        "Barangay Luka",
        "Barangay Mainit",
        "Barangay Manlum",
        "Barangay Nueva Caceres",
        "Barangay Poblacion",
        "Barangay Pungtod",
        "Barangay Tan-awan",
        "Barangay Tumalog",
    ],

    'tuburan' => [
        "Barangay Apalan",
        "Barangay Bagasawe",
        "Barangay Bagasawe",
        "Barangay Bakyawan",
        "Barangay Bulwang",
        "Barangay Carmen",
        "Barangay Daanlungsod",
        "Barangay Kabangkalan",
        "Barangay Kalangahan",
        "Barangay Kampingganon",
        "Barangay Kumalisquis",
        "Barangay Mag-Antoy",
        "Barangay Mahanlud",
        "Barangay Poblacion",
        "Barangay San Juan",
        "Barangay Sandayong",
        "Barangay Sto. Niño",
        "Barangay Siotes",
        "Barangay Tigbawan",
        "Barangay Tomonoy",
    ],
    'moalboal' => [
        "Barangay Agbalanga",
        "Barangay Bala",
        "Barangay Balabagon",
        "Barangay Basdiot",
        "Barangay Batadbatad",
        "Barangay Bugho",
        "Barangay Buguil",
        "Barangay Busay",
        "Barangay Lanao",
        "Barangay Poblacion East",
        "Barangay Poblacion West",
        "Barangay Saavedra",
        "Barangay Tomonoy",
        "Barangay Tuble",
        "Barangay Tunga",

    ],
    'aloguinsan' => [
        "Barangay Angilan",
        "Barangay Bojo",
        "Barangay Bonbon",
        "Barangay Esperanza",
        "Barangay Kandingan",
        "Barangay Kantabogon",
        "Barangay Kawasan",
        "Barangay Olango",
        "Barangay Poblacion",
        "Barangay Punay",
        "Barangay Rosario",
        "Barangay Saksak",
        "Barangay Tampa‑an",
        "Barangay Toyokon",
        "Barangay Zaragosa",

    ],
    'alegria' => [
        "Barangay Compostela",
        "Barangay Guadalupe",
        "Barangay Legaspi",
        "Barangay Lepanto",
        "Barangay Madridejos",
        "Barangay Montpeller",
        "Barangay Poblacion",
        "Barangay Santa Filomena",
        "Barangay Valencia ",
    ],
    'tuburan' => [
        "Barangay Alegria",
        "Barangay Amatugan",
        "Barangay Antipolo",
        "Barangay Apalan",
        "Barangay Bagasawe",
        "Barangay Bakyawan",
        "Barangay I",
        "Barangay II",
        "Barangay III",
        "Barangay VI",
        "Barangay V",
        "Barangay VI",
        "Barangay VII",
        "Barangay VIII",
        "Barangay Bulwang",
        "Barangay Caridad ",
        "Barangay Carmelo ",
        "Barangay Cogon ",
        "Barangay Colonia ",
        "Barangay Daan Lungsod ",
        "Barangay Fortaliza ",
        "Barangay Ga‑ang ",
        "Barangay Gimama‑a ",
        "Barangay Jagbuaya ",
        "Barangay Kabangkalan ",
        "Barangay Kabkaban ",
        "Barangay Kagba‑o ",
        "Barangay Kalangahan ",
        "Barangay Kamansi ",
        "Barangay Kampoot ",
        "Barangay Kan‑an ",
        "Barangay Kanlunsing ",
        "Barangay Kansi ",
        "Barangay Kaorasan ",
        "Barangay Libo ",
        "Barangay Lusong ",
        "Barangay Macupa ",
        "Barangay Mag‑alwa ",
        "Barangay Mag‑antoy ",
        "Barangay Mag‑atubang ",
        "Barangay Maghan‑ay ",
        "Barangay Mangga ",
        "Barangay Marmol ",
        "Barangay Molobolo ",
        "Barangay Montealegre ",
        "Barangay Putat ",
        "Barangay San Juan ",
        "Barangay Sandayong ",
        "Barangay Santo Niño ",
        "Barangay Siotes ",
        "Barangay Sumon ",
        "Barangay Tominjao ",
        "Barangay Tomugpa ",
        
    ],
    'ginatilan' => [
        "Barangay Anao",
        "Barangay Cagsing",
        "Barangay Calabawan",
        "Barangay Cambagte",
        "Barangay Campisong",
        "Barangay Cañorong",
        "Barangay Guiwanon",
        "Barangay Looc",
        "Barangay Malatbo",
        "Barangay Mangaco",
        "Barangay Palanas",
        "Barangay Poblacion",
        "Barangay Salamanca",
        "Barangay San Roque",
    ],

    'balamban' => [
        "Barangay Abucayan",
        "Barangay Aliwanay",
        "Barangay Arpili",
        "Barangay Baliwagan",
        "Barangay Bayong",
        "Barangay Biasong",
        "Barangay Buanoy",
        "Barangay Cabagdalan",
        "Barangay Cabasiangan",
        "Barangay Cambuhawe",
        "Barangay Cansomoroy",
        "Barangay Cantibas",
        "Barangay Cantuod",
        "Barangay Duangan",
        "Barangay Gaas",
        "Barangay Ginatilan",
        "Barangay Hingatmonan",
        "Barangay Lamesa",
        "Barangay Liki",
        "Barangay Luca",
        "Barangay Matun-og",
        "Barangay Nangka",
        "Barangay Pondol",
        "Barangay Prenza",
        "Barangay Santa Cruz-Santo Niño",
        "Barangay Singsing",
        "Barangay Sunog",
        "Barangay Vito",
    ],

    'poro' => [
        "Barangay Adela",
        "Barangay Altavista",
        "Barangay Cagcagan",
        "Barangay Cansabusab",
        "Barangay Daan Paz",
        "Barangay Eastern Poblacion",
        "Barangay Esperanza",
        "Barangay Libertad",
        "Barangay Mabini",
        "Barangay Mercedes",
        "Barangay Pagsa",
        "Barangay Paz",
        "Barangay Rizal",
        "Barangay San Jose",
        "Barangay Santa Rita",
        "Barangay Teguis",
        "Barangay Western Poblacion",
    ],

    'sanfrancisco' => [
        "Barangay Cabunga-an",
        "Barangay Campo",
        "Barangay Consuelo",
        "Barangay Esperanza",
        "Barangay Heminsulan",
        "Barangay Montealegre",
        "Barangay Northern Poblacion",
        "Barangay San Isidro",
        "Barangay Santa Cruz",
        "Barangay Santiago",
        "Barangay Sonog",
        "Barangay Southern Poblacion",
        "Barangay Unidos",
        "Barangay Union",
        "Barangay Western Poblacion",
    ],

    'tudela' => [
        "Barangay Buenavista",
        "Barangay Calmante",
        "Barangay Daan Secante",
        "Barangay General",
        "Barangay McArthur",
        "Barangay Northern Poblacion",
        "Barangay Puertobello",
        "Barangay Santander",
        "Barangay Secante Bag-o",
        "Barangay Southern Poblacion",
        "Barangay Villahermosa",
    ],

    'pilar' => [
        "Barangay Cabunga-an",
        "Barangay Campo",
        "Barangay Consuelo",
        "Barangay Esperanza",
        "Barangay Heminsulan",
        "Barangay Montealegre",
        "Barangay Northern Poblacion",
        "Barangay San Isidro",
        "Barangay Santa Cruz",
        "Barangay Santiago",
        "Barangay Sonog",
        "Barangay Southern Poblacion",
        "Barangay Unidos",
        "Barangay Union",
        "Barangay Western Poblacion",
    ],

    'danao' => [
        "Barangay Baliang",
        "Barangay Bayabas",
        "Barangay Binaliw",
        "Barangay Cabungahan",
        "Barangay Cagat-Lamac",
        "Barangay Cahumayan",
        "Barangay Cambanay",
        "Barangay Cambubho",
        "Barangay Cogon-Cruz",
        "Barangay Danasan",
        "Barangay Dungga",
        "Barangay Dunggoan",
        "Barangay Guinacot",
        "Barangay Guinsay",
        "Barangay Ibo",
        "Barangay Langosig",
        "Barangay Lawaan",
        "Barangay Licos",
        "Barangay Looc",
        "Barangay Magtagobtob",
        "Barangay Malapoc",
        "Barangay Manlayag",
        "Barangay Mantija",
        "Barangay Masaba",
        "Barangay Maslog",
        "Barangay Nangka",
        "Barangay Oguis",
        "Barangay Pili",
        "Barangay Poblacion",
        "Barangay Quisol",
        "Barangay Sabang",
        "Barangay Sacsac",
        "Barangay Sandayong Norte",
        "Barangay Sandayong Sur",
        "Barangay Santa Rosa",
        "Barangay Santican",
        "Barangay Sibacan",
        "Barangay Suba",
        "Barangay Taboc",
        "Barangay Taytay",
        "Barangay Togonon",
        "Barangay Tuburan Sur",
    ],

];